name: "iPod Thermostat"
version: "1.1.11" # Change la version pour forcer HA à voir la modif
slug: "ipod_thermostat"
description: "Interface Node.js pour thermostat"
icon: "ipod.png"
arch:
  - aarch64
  - armv7
init: false
hassio_api: true
ingress: true
ingress_port: 8080 
panel_icon: "mdi:ipod"
panel_title: "iPod"
options:
  ha_token: "" # On le laisse vide par défaut
  ha_url: "http://homeassistant.local:8123" # URL par défaut de Home Assistant
schema:
  ha_token: str # On dit que c'est une chaîne de caractères
  ha_url: str # On dit que c'est une chaîne de caractères
ports:
  8080/tcp: 8080 